### ISSUE TITLE
2.11.2: "[" and "]" becomes "[[]" and "[]]"

### ISSUE THREAD

**Issue by PhonyWelder** [kornelski/pngquant#282]
`pngquant "t[e]st.png" --output "t[e]st2.png"` makes "t[[]e[]]st2.png" file.
no bug in 2.10.1

BTW, old windows binary on https://pngquant.org/ - 2.11.2 instead of 2.11.4

**Comment by kornelski** [comment]
Thanks for the report.

**Comment by kornelski** [comment]
Fixed in 2.11.7
