### ISSUE TITLE
latest pngquant crash on windows x64 10 1709

### ISSUE THREAD

**Issue by phonphen** [kornelski/pngquant#283]
![latest - copy](https://user-images.githubusercontent.com/25279951/35142755-da925d5e-fd31-11e7-8d80-fb2c86f0c156.png)

![error - copy](https://user-images.githubusercontent.com/25279951/35142760-df25d468-fd31-11e7-8520-1ea08a55ab33.png)

**Comment by kornelski** [comment]
Please try 2.11.7

**Comment by phonphen** [comment]
ok, its fixed now 
thanks 😄
