### ISSUE TITLE
test failure with libimagequant-2.11.6

### ISSUE THREAD

**Issue by manisandro** [kornelski/pngquant#284]
pngquant-2.11.6 crashes when run with libimagequant-2.11.6, i.e. from the pngquant  test suite:

    gdb --args ./pngquant /tmp/pngquantOSdZQg/overwritetest.png
    Thread 1 "pngquant" received signal SIGSEGV, Segmentation fault.
    0x0000000000000000 in ?? ()
    (gdb) bt full
    #0  0x0000000000000000 in ?? ()
    No symbol table info available.
    #1  0x00007ffff7bcf5ed in liq_image_get_row_rgba (row=0, img=0x555555761320, img@entry=0x0) at libimagequant.c:770
            temp_row = 0x0
            row = 0
            img = 0x555555761320
            temp_row = <optimized out>
            temp_row = <optimized out>
            temp_row = <optimized out>
    #2  convert_row_to_f (img=img@entry=0x555555761320, row_f_pixels=0x7ffff7e19020, row=row@entry=0, 
        gamma_lut=gamma_lut@entry=0x7fffffffc340) at libimagequant.c:782
            row_pixels = <optimized out>
    #3  0x00007ffff7bcf68e in liq_image_get_row_f_init (img=img@entry=0x555555761320) at libimagequant.c:802
            i = 0
            gamma_lut = {0, 0.00122643623, 0.00283675198, 0.00463287858, 0.00656141946, 0.00859481283, 0.0107158683, 0.0129127111, 
            0.0151765905, 0.01750076, 0.0198798385, 0.0223094262, 0.0247858483, 0.0273059849, 0.0298671555, 0.0324670188, 
            0.0351035185, 0.0377748348, 0.0404793322, 0.0432155468, 0.0459821485, 0.0487779342, 0.0516017973, 0.054452721, 
            0.0573297702, 0.0602320842, 0.0631588623, 0.0661093518, 0.0690828562, 0.0720787272, 0.0750963464, 0.0781351477, 
            0.0811945871, 0.0842741504, 0.0873733461, 0.0904917344, 0.093628861, 0.0967843309, 0.0999577418, 0.103148721, 
            0.106356904, 0.109581962, 0.112823568, 0.116081402, 0.119355172, 0.122644588, 0.125949368, 0.129269257, 0.132604003, 
            0.135953352, 0.139317065, 0.14269492, 0.146086708, 0.149492204, 0.152911201, 0.156343505, 0.159788936, 0.163247287, 
            0.166718394, 0.170202076, 0.173698172, 0.177206516, 0.18072693, 0.184259281, 0.187803417, 0.191359192, 0.194926456, 
            0.198505074, 0.202094927, 0.205695853, 0.20930776, 0.212930501, 0.216563955, 0.220208019, 0.223862559, 0.227527484, 
            0.231202677, 0.234888017, 0.238583416, 0.242288768, 0.246003971, 0.249728933, 0.253463537, 0.257207721, 0.260961384, 
            0.264724433, 0.268496782, 0.272278339, 0.276069015, 0.279868752, 0.283677429, 0.287495017, 0.291321427, 0.295156538, 
            0.299000353, 0.30285272, 0.306713611, 0.310582966, 0.314460665, 0.318346679, 0.322240949, 0.326143414, 0.330053955, 
            0.333972573, 0.337899178, 0.341833711, 0.345776081, 0.34972629, 0.353684247, 0.357649922, 0.361623198, 0.365604073, 
            0.369592488, 0.373588353, 0.37759167, 0.381602347, 0.385620356, 0.389645636, 0.393678129, 0.397717804, 0.401764601, 
            0.405818492, 0.409879386, 0.413947314, 0.418022156, 0.422103912, 0.426192492, 0.430287927, 0.434390098, 0.438499004, 
            0.442614615, 0.446736872, 0.450865716, 0.455001146, 0.459143072, 0.463291526, 0.467446417, 0.471607715, 0.475775391, 
            0.479949415, 0.484129727, 0.488316327, 0.492509127, 0.496708155, 0.500913322, 0.505124688, 0.509342074, 0.51356554, 
            0.517795026, 0.522030592, 0.526272058, 0.530519426, 0.534772754, 0.539031923, 0.543296993, 0.547567844, 0.551844478, 
            0.556126833, 0.56041497, 0.564708769, 0.569008231, 0.573313355, 0.577624083, 0.581940353, 0.586262226, 0.590589643, 
            0.594922543, 0.599260926, 0.603604794, 0.607954085, 0.612308741, 0.616668761, 0.621034145, 0.625404894, 0.629780948, 
            0.634162247, 0.638548791, 0.642940581, 0.647337556, 0.651739776, 0.656147122, 0.660559595, 0.664977193, 0.669399917, 
            0.673827648, 0.678260505, 0.682698369, 0.68714118, 0.691589057, 0.696041882, 0.700499594, 0.704962313, 0.70942986, 
            0.713902354, 0.718379676, 0.722861826, 0.727348864, 0.73184067, 0.736337245, 0.740838587...}
    #4  0x00007ffff7bcf739 in remap_to_palette (input_image=input_image@entry=0x555555761320, 
        output_pixels=output_pixels@entry=0x5555557623d0, map=0x555555769c10) at libimagequant.c:1227
            rows = 287
            cols = 380
            remapping_error = 0
            acolormap = <optimized out>
            n = <optimized out>
            transparent_index = <optimized out>
            max_threads = <optimized out>
            average_color = <optimized out>
    #5  0x00007ffff7bd280f in liq_write_remapped_image_rows (quant=0x555555763440, input_image=0x555555761320, 
    ---Type <return> to continue, or q <return> to quit---
        row_pointers=0x5555557623d0) at libimagequant.c:2080
            generate_dither_map = true
            result = <optimized out>
            remapping_error = 0.000148334468
            quant = 0x555555763440
            i = <optimized out>
            generate_dither_map = <optimized out>
            row_pointers = 0x5555557623d0
            input_image = 0x555555761320
            result = <optimized out>
            remapping_error = <optimized out>
            result = <optimized out>
            remapping_error = <optimized out>
            i = <optimized out>
            generate_dither_map = <optimized out>
    #6  0x0000555555558457 in pngquant_main._omp_fn.0 () at pngquant.c:457
            options = 0x7fffffffd770
            latest_error = SUCCESS
            file_count = 0
            error_count = 0
            skipped_count = 0
    #7  0x00007ffff6f6dcff in GOMP_parallel () from /lib64/libgomp.so.1
    No symbol table info available.
    #8  0x0000555555558d5e in pngquant_main (options=0x7fffffffd770) at pngquant.c:336
            error_count = 0
            skipped_count = 0
            file_count = 0
            latest_error = SUCCESS
    #9  0x00005555555571b5 in main (argc=<optimized out>, argv=<optimized out>) at pngquant.c:204
            options = {liq = 0x55555575f290, fixed_palette_image = 0x0, log_callback = 0x0, log_callback_user_info = 0x0, 
            quality = 0x0, extension = 0x55555555ba57 "-fs8.png", output_file_path = 0x0, map_file = 0x0, files = 0x7fffffffd960, 
            num_files = 1, colors = 0, speed = 0, posterize = 0, floyd = 1, using_stdin = false, using_stdout = false, 
            force = false, fast_compression = false, min_quality_limit = false, skip_if_larger = false, strip = false, 
            iebug = false, last_index_transparent = false, print_help = false, print_version = false, missing_arguments = false, 
            verbose = false}
            retval = <optimized out>

Seems related to LIQ_TEMP_ROW_WIDTH between libimagequant-2.11.4 and libimagequant-2.11.6.

**Comment by kornelski** [comment]
Fixed in the next version
