### ISSUE TITLE
Support for Animated PNG

### ISSUE THREAD

**Issue by matjazu** [kornelski/pngquant#288]
I can't find any information about support of animated PNG images (https://en.wikipedia.org/wiki/APNG). Is it supported in pngquant or is possible to add support for it?

What are the options here?

Tnx

**Comment by kornelski** [comment]
The underlying libimagequant has a histogram API to support making a shared palette for many images.

However, the pngquant CLI command uses libpng, so it doesn't understand APNG. 

If you're writing a tool, then you should be able to combine libimagequant with APNG reading/writing library.

If you're only a user of CLI binary, then you'll probably need a 3rd party tool that can convert APNG to and from a single flat PNG filmstrip.

**Comment by matjazu** [comment]
Ok, thank you for the info.

**Comment by Kristinita** [comment]
@kornelski, **Type: Question** :question:

Is any chance, that `.apng` support will be implemented to pngquant?

I couldn't find any tool for lossy compression of `.apng` images.

Thanks.

**Comment by kornelski** [comment]
Maybe, but I'm not planning this in the near future.

**Comment by phocks** [comment]
At the moment pngquant seems to break animated pngs by only saving the first frame. Is there any possibility that if it detects an animated png to give it a flag like --ignore-animated that will simply ignore that file?

**Comment by Zipdox2** [comment]
For anyone who stumbles across this, you can use pngquant on the individual frames and then use FFmpeg to combine the frames, which will increase the overall size a bit but will still be useful.

For example:
```
ffmpeg -r 8 -i %02d.png -plays 0 -vf format=rgba -f apng combined.png
```

Alternatively you can use FFmpeg's palettegen filter to generate a palette and use the paletteuse filter to make the APNG. The only problem with this is that palettegen only uses one transparent color (resulting in hard edges), and is limited to 256 colors.
