### ISSUE TITLE
Issue in recursive processing

### ISSUE THREAD

**Issue by pointerphile** [kornelski/pngquant#293]
OS : macOS 10.13.3
GNU bash version : 3.2.57(1)
Xcode version : 9.2(Apple LLVM version 9.0.0)
Boost version : 1.66.0
pngquant version : 2.11.7

pngquant absolute path :
/Users/pointerphile/Desktop/pngquant-openmp

source png path :
/Users/pointerphile/Desktop/temp

there are 10 png images in directory.
you can download source images : 
https://drive.google.com/file/d/1UO9Jdf6bgp7zbqS-C3gFY2aFllXWbTTT/view?usp=sharing

in terminal,

> ps-MacBook-Pro:~ pointerphile$ /Users/pointerphile/Desktop/pngquant-openmp /Users/pointerphile/Desktop/temp/*.png				// It works. :)

> ps-MacBook-Pro:~ pointerphile$ /Users/pointerphile/Desktop/pngquant-openmp "/Users/pointerphile/Desktop/temp/*.png"				// It failed... :(
  error: cannot open /Users/pointerphile/Desktop/temp/*.png for reading
ps-MacBook-Pro:~ pointerphile$

in Xcode,

`#include <iostream>`
`#include <cstdlib>`
`#include <string>`
`#include <boost/process.hpp>`
`#include <boost/filesystem.hpp>`

`int main(int argc, char * argv[])`
`{`
`	std::string cmd0 = "/Users/pointerphile/Desktop/pngquant-openmp /Users/pointerphile/Desktop/temp/*.png";`
`	std::string c0 = "/Users/pointerphile/Desktop/pngquant-openmp";`
`	std::string c1 = "/Users/pointerphile/Desktop/temp/*.png";`
	
`	//It works :)`
`	std::system(cmd0.c_str());`

`	//but when I tried to use boost::process, it faild :(`
`	//boost::process::child command0(cmd0.c_str());`
`	//command0.wait();`

`	//It failed too...`
`	//boost::process::child command1(c0.c_str(), c1.c_str());`
`	//command1.wait();`
`	//and said "error: cannot open /Users/pointerphile/Desktop/temp/*.png for reading"`

`	return 0;`
`}`

**Comment by kornelski** [comment]
That's because `*` is not handled by pngquant. It's replaced by `bash`. If you launch `pngquant` directly without `bash`, there's no support for bash's special wildcard syntax.

So either scan files yourself in your wrapper program, or launch `bash` that runs a script that launches `pngquant` (but be super careful if you use paths/filenames from untrusted usres, since bash escaping is hard, and any mistakes create arbitrary code execution vulnerabilities).

**Comment by pointerphile** [comment]
Tested again in
Command Prompt(cmd.exe)
Windows 10
Visual Studio 2017

and the wildcard `* `works great.

Okay, I'll try to figure out the solution in Xcode myself.
Thank you.

**Comment by kornelski** [comment]
Yeah, because Windows' cmd.exe is all around awful and doesn't support wildcards, I fake wildcards on Windows only.
