### ISSUE TITLE
About GPL

### ISSUE THREAD

**Issue by pointerphile** [kornelski/pngquant#295]
Hello,
I programmed my own program. It use your pngquant binary for macOS.
My program use boost process library(like fork() and exec()) to run pngquant to get optimized pngs.
I don't use and fix your pngquant's source code, just use executable binary.
Should I follow GPL?

regards
pointer

**Comment by kornelski** [comment]
If you're just launching an executable, then GPL applies only to that executable, not your program.

**Comment by pointerphile** [comment]
Understood.
Thank you for your help.
