### ISSUE TITLE
If my directory or file name contains Chinese, it will fail

### ISSUE THREAD

**Issue by DemoCap** [kornelski/pngquant#301]
If my directory or file name contains Chinese, it will fail
![image](https://user-images.githubusercontent.com/18241019/40570443-95edbc26-60bd-11e8-8cfd-8b9cd8004e7c.png)

**Comment by linchenrr** [comment]
I have got the same problem.
version 2.11.7

run the test.bat

[pngquant.zip](https://github.com/kornelski/pngquant/files/2056604/pngquant.zip)

**Comment by kornelski** [comment]
This is a known problem. I've switched to Microsoft's own compiler, and Microsoft's standard C library has this bug.

#265
