### ISSUE TITLE
Unexpected color changing 

### ISSUE THREAD

**Issue by sjwilliams** [kornelski/pngquant#302]
Hi, we use `pngquant` on the graphics desk at The New York Times as part of an automated workflow for certain web graphics coming out of Adobe Illustrator. 

On a [recent project](https://www.nytimes.com/interactive/2018/06/08/sports/worldcup/fifa-vote-world-cup-2026-host.html), we noticed that one of the four renditions of a map we exported (we use different sizes for various viewport widths) and passed through `pngquant` had a color shift in a part of the map that changed the meaning of the graphic. 

We expected Morocco to be red:
![image](https://user-images.githubusercontent.com/294614/41358910-5898503c-6ef7-11e8-84b6-e13580e1916e.png)

But instead it came out purple: 
![image](https://user-images.githubusercontent.com/294614/41358879-4c0c963e-6ef7-11e8-9061-54eca151b0a4.png)

Our automated workflow essentially does this to the Illustrator pngs:
```
pngquant --quality=65-80 *.png
```

If we change the quality settings higher than 80 all maps render correctly. As we test setting below 65 more renditions exhibit the color shift. 

Perhaps we misunderstood how the quality range parameter impacts the outputted file. Is this simplified color palette the expected behavior as pngquant outputs optimized versions or did we stumble across an issue? 

We're using `2.12.0` via Homebrew with `Little CMS` and `libpng 1.6.34`.

Here are the source files straight out of Illustrator:
https://static01.nyt.com/newsgraphics/2018/06/15/pngquant/map-300.png
https://static01.nyt.com/newsgraphics/2018/06/15/pngquant/map-460.png
https://static01.nyt.com/newsgraphics/2018/06/15/pngquant/map-720.png
https://static01.nyt.com/newsgraphics/2018/06/15/pngquant/map-1050.png

The `map-460.png` file is the one that color shifts. You can see the the post-processed file here: https://static01.nyt.com/newsgraphics/2018/06/15/pngquant/map-460-quality65-80.png

Thanks!

cc @giratikanon

**Comment by chrissimpkins** [comment]
It looks like your original image is an 8-bit PNG with 111 colors.  With those quality range settings, pngquant is dropping the image file to a 2-bit PNG with 3 colors.  

```
OK: map-460.png (920x2420, 8-bit palette, non-interlaced, 97.3%).
OK: map-460-quality65-80.png (920x2420, 2-bit palette, non-interlaced, 95.3%)
```

It looks like you are instructing pngquant to be "too" lossy with this command for this image.

Here is Kornel's documentation on the `--quality` flag:

```
--quality min-max          don't save below min, use fewer colors below max (0-100)
```

Try increasing the upper bound of the range that instructs pngquant to decrease the color number to reduce image quality below your defined level.  If I run the following on your original file (note increased upper bound):

```
$ pngquant --quality=65-90 map-460.png
```

I get a 2-bit PNG file with 4 colors and the red color is present again.  The file is under 100 bytes larger than your optimized version with the quality settings using the range `65-80`.

![map-460-fs8](https://user-images.githubusercontent.com/4249591/41490975-84e23954-70c4-11e8-80e7-e5e2a9c576cc.png)

**Comment by kornelski** [comment]
Try `--quality=65-100`. Using max quality below 100 asks pngquant to drop colors, so it will drop them.

**Comment by kornelski** [comment]
Thanks for the report.

It's an interesting case, since it exposes weakness in measurement of quality using mean square error. Even a big change to the small area, when averaged with all the perfectly matched background, mathematically still seems "90%" accurate.

I already have some workarounds for such cases, but I'll see if I can tune them better.

In the meantime the workaround is to use `--quality=65-100`, so that pngquant isn't required to drop any colors when not necessary.

**Comment by sjwilliams** [comment]
@chrissimpkins, @kornelski Thanks for the info!

So  `--quality=65-100` will never change our graphics in a meaningful way, with the tradeoff being larger file sizes than the settings we currently have. Thanks for the clarification. We'll take larger files over inaccurate journalism!

**Comment by chrissimpkins** [comment]
> We'll take larger files over inaccurate journalism!

@sjwilliams Your readers will appreciate the extra effort to make them as small as possible without perceptible loss of quality though, particularly all of those readers on mobile devices.
