### ISSUE TITLE
Any way to pass Binary to pngquant.exe from C# code?

### ISSUE THREAD

**Issue by linchenrr** [kornelski/pngquant#305]
Because the issues that file name cannot contains Chinese #301 
I want to read the original png file from my own tool written by C# and pass the Binary to pngquant.exe,
Here is the way I use pngquant.exe in the old way which doesn't support chinese filename. 

![1](https://user-images.githubusercontent.com/11712968/42435415-094f1208-8389-11e8-8963-8c947476a081.png)

I hope I can pass originalBytes in and read output Binary in C# then I can handle that problem.

**Comment by kornelski** [comment]
Yes, you can do that. Instead of input file path specify `-` and pngquant will read binary from standard input.

I don't know C#, so I can't help you how to send a file through standard input.
