### ISSUE TITLE
png alphapremultiplied error

### ISSUE THREAD

**Issue by haroel** [kornelski/pngquant#307]
-   I used Pngyu to compress those png files, it works ok。
-  well,  I want to deloy a jenkins work flow,  so  I need commandline tools.  

   1.  `brew install pngquant` (v2.12.0 (January 2018) )  

   2.  write a shell command `find ${project_build_path} -name '*.png' -exec pngquant --ext .png --force --nofs --speed 3 256 {} \;`  ,   when my game start,  the png which open `alphapremultiplied `  is bad.  
![8ed8b592-2d53-468a-8373-ed171891585c](https://user-images.githubusercontent.com/2418222/43185603-f1c8792e-901e-11e8-91d0-fdc09b497ea1.png)

3. so, I copy the pngquant from `/Applications/Pngyu.app/Contents/Resources/pngquant`  ( 1.8.1 (November 2012) ), then use the same shell ,it works.

![b7098373-97b5-4ab5-9d4d-81cd6835a507](https://user-images.githubusercontent.com/2418222/43185635-0a78e472-901f-11e8-8ccf-5ef8c54dbb0b.png)

**Comment by kornelski** [comment]
Can you post the original unconverted file?
