### ISSUE TITLE
Cyrillic letters on Windows

### ISSUE THREAD

**Issue by russdreamer** [kornelski/pngquant#317]
Hi. 
If input or output path contains cyrilic letters - it can not read the file. I have this problem on Windows 10, and no problem on MacOS. Haven't tried on other unix systems.

<img width="1008" alt="screenshot 2018-11-20 at 07 29 13" src="https://user-images.githubusercontent.com/10559538/48751555-0b156080-ec96-11e8-955d-72e9c2b90023.png">

**Comment by kornelski** [comment]
This is a known problem with Windows #275
