### ISSUE TITLE
Unable to build pngquant using the release tar.gz file (2.12.1)

### ISSUE THREAD

**Issue by kongakong** [kornelski/pngquant#326]
I downloaded the https://github.com/kornelski/pngquant/archive/2.12.1.tar.gz from the link shown on release page.

I untar and then run  `./configure`

Here is the error I got

```
  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
If you're using git, do clone with --recursive, or download from https://github.com/ImageOptim/libimagequant
imagequant: error ... libimagequant.h not found in ./lib/ 
```

Could you re-release a tar file which fixes this issue?

**Comment by kornelski** [comment]
No, archives auto-crated by github are garbage. Don't use them.

Correct sources are only at https://pngquant.org/releases.html

**Comment by kongakong** [comment]
Thanks! Also a big thank-you for developing and supporting this wonderful tool!

I am closing the ticket.
