### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by svenewers** [kornelski/pngquant#329]
Hey maintainers,  

I was wondering if I could get some clarification on your interpretation of GPLv3 that this project is licensed under.  

Here's my situation: I'm currently developing a macOS & Windows 10 application that's meant to help web-developers with optimising their websites for speed. The app isn't planned to be released under the GPL but I'd like to use pngquant to give the developers using the app a direct way to compress PNGs in a lossy way.  
  
Would you consider including the pre-build binary of pngquant in the app's resources & then calling pngquant via its CLI interface "communicating at arms length", as the GPL / GNU website would call it, and therefore okay to do, or would you expect me to contact you for a separate commercial licensing arrangement for this use-case.  

Any guidance on this question would be much appreciated.

**Comment by kornelski** [comment]
If you distribute pngquant, then GPL applies. If you use it only personally on your machine, then it doesn't.

If your application is free, I'm happy to give you a license for distribution.

**Comment by svenewers** [comment]
@kornelski Thanks for that clarification. Will contact you off-Github for more.

**Comment by svenewers** [comment]
@kornelski Thanks for that clarification. Will contact you off-Github for more.
