### ISSUE TITLE
error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kushagra8888** [kornelski/pngquant#333]
OS: Ubuntu 19.04

I encounter this error when I try to use image-webpack-loader, a project which uses pngquant as a dependency. An issue has already been filed there. https://github.com/tcoopman/image-webpack-loader/issues/93

Unfortunately the suggested workaround there do not seem to work for Ubuntu 19...

```
Error: /home/kushagra/work/clarisights/adwyze-frontend/node_modules/pngquant-bin/vendor/pngquant: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

**Comment by kornelski** [comment]
This binary is trying to load libpng 1.2, which is an old buggy version that nobody should be using anymore. 

You have to build the executable with libpng 1.6 or later.

**Comment by Kushagra8888** [comment]
Thank you!
