### ISSUE TITLE
color issues in game picture

### ISSUE THREAD

**Issue by Lee-lithium** [kornelski/pngquant#335]
i use pngquant compress some anime game picture
but some picture have a little issues
in attach file (picture have some safe modify)
uncompress.png (RGBA32) eyes color is blue
but compressed.png (PAL8)  eyes color is green
[attach.zip](https://github.com/kornelski/pngquant/files/3431708/attach.zip)

i compress a lot of game , i found two or three game have the same issue
compressed png is fine, but a little part have color issues

i need to change my Options? or have other solution?
i try a old version pngquant, have the same issue 

pngquant Version 2.12.3
Options:
--force 
--speed 1 
--quality 80-100 
--strip 
--verbose

**Comment by kornelski** [comment]
The input file has a `cHRM` chunk which defines its color space. You must compile pngquant with LCMS2 to support this properly.

Run pngquant -h to see if color profiles are supported.

>  Color profiles are supported via Little CMS. Using libpng 1.6.37.

If they are, the result is correct:

![uncompress-fs8](https://user-images.githubusercontent.com/72159/61888003-a3857400-aefa-11e9-9dc5-780420b17976.png)

**Comment by Lee-lithium** [comment]
![color profiles](https://user-images.githubusercontent.com/16644101/61900426-2a187080-af50-11e9-8710-adbbcd64f666.jpg)
i'm so sorry, this my fault
that attach picture can't correct reproduce issue
i upload new attach, Hope that picture doesn't offend you...

01_uncompress (RGBA32) // left red hair character is blue eyes
01_compressed (PAL8)     // left red hair character is green eyes 

02_uncompress(RGBA32) //right red hair character is blue eyes
02_compressed(PAL8)     //right red hair character is green eyes

and in 02_compressed picture compressed quality is very low
have a lot of quality loss in this picture
i have wrong options? or 02_compresse is not applicable to pngquant?

[attach.zip](https://github.com/kornelski/pngquant/files/3432866/attach.zip)

 pngquant is a amazing tool, thanks your help

**Comment by kornelski** [comment]
As part of a larger image this distortion does make sense. There's a lot more green colors in the image and they get unified. It's a limitation of the algorithm.

**Comment by Lee-lithium** [comment]
thanks your help , i  understand
can you suggest me another lossy png compress tool or method?

i try some compress tool to compress png
the pngquant is very useful
i compress a lot of game only a few png picture get this issue

**Comment by zvezdochiot** [comment]
@Lee-lithium say> can you suggest me another lossy png compress tool or method?

https://github.com/foobaz/lossypng

**Comment by kornelski** [comment]
Try https://imageoptim.com/online - it handles that picture well.

**Comment by Lee-lithium** [comment]
thanks you kornelski and zvezdochiot
i think this issue is solved
