### ISSUE TITLE
add output options png rgba32 

### ISSUE THREAD

**Issue by Lee-lithium** [kornelski/pngquant#337]
sorry bother you again
i use https://imageoptim.com/online compress png
but compressed png compression ratio is bad (2kb~30kb)

i find another png compress tool kornelski/mediancut-posterizer
that output rgba32 png and solved my color issue
but output quality is not like pngquant
have some quality loss

i test some art picture 
pngquant
have a lot of color picture (RGBA32) -> (PAL8) get issue
less color picture               (RGBA32) -> (PAL8) no issue or issue is not obvious

mediancut-posterizer
have a lot of color picture (RGBA32) -> (RGBA32) no color issue, but have some quality loss

i think use pngquant compress and output file is png RGBA32 can solved some color issue

**Comment by kornelski** [comment]
Use `--quality` and `--skip-if-larger` options in pngquant, and fallback to the posterizer when pngquant skips the file.

**Comment by Lee-lithium** [comment]
I read pngquant source code, pngquant algorithm is base on 8bit palette
I understand my request is ridiculous, I'm sorry about that

I use mediancut-posterizer and pngquant compress some picture
some factor will effect output picture quality
picture include element and color, picture creator color style
I think your method is best solution.

I have a little question, mediancut-posterizer this tool is still update?

**Comment by kornelski** [comment]
I don't actively work on mediancut-posterizer any more, but it should work.

**Comment by Lee-lithium** [comment]
the issue has finish, close issue
thank you very much :)
