### ISSUE TITLE
Multi-scale Probabilistic Dithering?

### ISSUE THREAD

**Issue by LynxTWO** [kornelski/pngquant#341]
Came across this when looking for a way to avoid dithering and keep file-size to a minimum on problem images.  Banding would look similar to the attached example, which is more natural to the human eye...

http://vigir.missouri.edu/~gdesouza/Research/Conference_CDs/IEEE_ICIP_2007/pdfs/0400397.pdf

![banding](https://user-images.githubusercontent.com/23408044/64076240-4d8db400-cc90-11e9-8b64-2202a0fbfbaa.png)

**Comment by kornelski** [comment]
That method is not applicable to compression of images. It's a post-processing method to be run after decompression, so pngquant can't do it. It'd have to be implemented in image viewers.
