### ISSUE TITLE
Transparent pixels are not transparent anymore when using color blend...

### ISSUE THREAD

**Issue by BiggerWoo** [kornelski/pngquant#344]
I compressed 0.png
![0](https://user-images.githubusercontent.com/8098771/65825836-4e752e00-e2ae-11e9-9062-8bcb18ec86ba.png)
original↑

![0](https://user-images.githubusercontent.com/8098771/65826031-d2301a00-e2b0-11e9-8538-17b0a700777f.png)
compressed↑

and trying to do some color blend with it,
it works fine with src blend factor is "src_alpha"
![0](https://user-images.githubusercontent.com/8098771/65825843-65b41b80-e2ae-11e9-8b47-24b7b625c023.png)
but when I change it into "src_color"
![1](https://user-images.githubusercontent.com/8098771/65825848-7d8b9f80-e2ae-11e9-9564-decb4b00cd52.png)
looks like transparent pixels are not transparent anymore.
but wait! it still works fine with this
![1](https://user-images.githubusercontent.com/8098771/65825858-8ed4ac00-e2ae-11e9-8bca-e613c42a51ba.png)
after compressed:
![2](https://user-images.githubusercontent.com/8098771/65825862-972ce700-e2ae-11e9-84b4-30cc34f16f85.png)

so what happend with 0.png?

pngquant -v:
pngquant, 2.12.0 (January 2018), by Kornel Lesinski, Greg Roelofs.
   Color profiles are supported via Little CMS. Using libpng 1.6.35.
and with options:
    --ext=.png --force --nofs --skip-if-larger --speed=1 --quality=65-80

by the way, if I remove option --nofs, the same problem occured with 1.png after compressed
![3](https://user-images.githubusercontent.com/8098771/65825863-9dbb5e80-e2ae-11e9-8127-883fa8880e3f.png)
and I done this in cocosCreator, but it's not cocosCreator's problem right? :)

**Comment by kornelski** [comment]
The images look fine outside of cocosCreator, so it is cocosCreator's problem. Please let them know they need to improve handling of PNG8 with tRNS chunk.

**Comment by BiggerWoo** [comment]
ok ,thanks~~
