### ISSUE TITLE
Can you confirm that the input image is never overwritten in case pngquant fails?

### ISSUE THREAD

**Issue by cesaredamico** [kornelski/pngquant#345]
We'd like to use the original image if pngquant fails, but we're afraid it may get corrupted in case pngquant fails at any moment. Can you confirm that the original image is never overwritten if pngquant fails?
Thanks!

**Comment by zvezdochiot** [comment]
#342

**Comment by kornelski** [comment]
The file is replaced atomically on success, i.e. pngquant writes to a temp file and then renames it.

The exception is when you use shell stdout redirection `> file` syntax. This is then handled by the shell, not by pngquant.
