### ISSUE TITLE
image with transparency gets dithered 1bit image if quality is not set

### ISSUE THREAD

**Issue by pixeljunkie** [kornelski/pngquant#352]
I have some images where the source image is like:
PNG 648x600 648x600+0+0 8-bit DirectClass 503KB 0.000u 0:00.000 (imagemagick identify output)

If i use `pngquant --force --speed 3 --ext=.png` (with default quality) the image is compressed to a 5kb file, but with 1 greyscale color and dithered. So i'ts broken afterwards.
If i set any quality level above 1 the image gets compressed and the output is o.k. Level 1 produces the same output file.
This happened after an update to pngquant V. 2.12.5 (libpng 1.5.13)

My workaround is a setting of 85 as quality but shouldn't it work without any quality setting as before?
Looks like a bug for me. Like the default value changed to 1?

**Comment by pixeljunkie** [comment]
Because the quality setting is a range i tried different ranges. Everything works but as above, leaving the quality empty, leads to the veeeery compressed 1bit images.

**Comment by zvezdochiot** [comment]
@pixeljunkie say:
>If i use `pngquant --force --speed 3 --ext=.png`

Use `pngquant -v --force --speed 3 --ext=.png` and let me read the conclusion.

**Comment by pixeljunkie** [comment]
read 492KB file
made histogram...60841 colors found
selecting colors...7%
selecting colors...15%
selecting colors...61%
selecting colors...69%
selecting colors...100%
moving colormap towards local minimum
eliminated opaque tRNS-chunk entries...1 entry transparent
mapped image to new colors...MSE=1231.299 (Q=0)
writing 2-color image as test.png

**Comment by zvezdochiot** [comment]
https://github.com/kornelski/pngquant/blob/b54c2bc85865ff7e8a62d071da4dd2dd84d4e3da/pngquant.c#L481

This https://github.com/ImageOptim/libimagequant :

https://github.com/ImageOptim/libimagequant/blob/ca9057887e5c9ba989e176f957ce215bfc34bb1a/libimagequant.c#L1118-L1126

https://github.com/ImageOptim/libimagequant/blob/ca9057887e5c9ba989e176f957ce215bfc34bb1a/libimagequant.c#L249-L272

**Comment by zvezdochiot** [comment]
See #346

**Comment by kornelski** [comment]
This is caused by a bug in GCC 4. You need GCC 7 or later to compile pngquant correctly.

**Comment by zvezdochiot** [comment]
@kornelski say:
>This is caused by a bug in GCC 4.

```sh
gcc --version
gcc (Debian 4.7.2-5) 4.7.2
```
The flight is normal.

**Comment by kornelski** [comment]
I'm removing OpenMP usage that is being miscompiled. I've tried to use OpenMP more, but with such quality of implementation problems, and lack of thread-safety in C (that I'm used to in Rust), this is just too risky.
