### ISSUE TITLE
Windows CLI is not outputting compressed images

### ISSUE THREAD

**Issue by ankitsinghas** [kornelski/pngquant#355]
I downloaded a command-line binary for Windows, run it from CMD, but the problem is that it is not outputting compressed images. All commands are working properly, but when I run an image compression command like "**pngquant --quality=65-80 png_original.png**", the command does not print any errors and I not get a compressed image.
what's the problem?
Im running Windows 10 1909 Pro 64-bit.
![111](https://user-images.githubusercontent.com/7056967/78869274-ecb62d80-7a61-11ea-9247-9a7943f1e192.PNG)

**Comment by kornelski** [comment]
This is normal behavior. By setting quality to at least 65 you tell the program to *not* compress anything if compression happens to lower quality more than that.

Use `--quality=0-80` to always compress.
