### ISSUE TITLE
How to preserve the timestamps of files on macOS 10.15.6 using pngquant 1.1

### ISSUE THREAD

**Issue by jagdishadusumalli** [kornelski/pngquant#360]
I have screenshots taken from 2016 and after and dont want to loose the timestamps of the files after optimization
i know the filenames have the datetime info but i rely on file meta info.

I ran the command as many ways as below
pngnq ~/Desktop/*.png (creates new files)
pngnq -f -e .png ~/Desktop/*.png (replaces the old files)

All optimized files have Created/ Modified/ Added date set as Today after the processing.

I tried pngnq and it has a -p flag (preserve timestamps) and it works perfectly but the quality is a bit low

How can we keep the old timstamps preserved on files with pngquant?

**Comment by zvezdochiot** [comment]
Hi @jagdishadusumalli .

Use `stat` and `touch`.

**Comment by kornelski** [comment]
No, unfortunately there's no option to preserve timestamps.

**Comment by jagdishadusumalli** [comment]
Hi @kornelski Can we please add this into our "Feature Requests".
Will be a worth addition to this great tool.

**Comment by prakash-partho** [comment]
Hello @kornelski 
I also request to have an option to preserve timestamps.

**Comment by tobias992** [comment]
Hello Devs,
any news with the --preserve option? To leave the old file attributes would be a very nice and helpful feature.

**Comment by ReessKennedy** [comment]
+1 but I also wrote some code that does this: https://www.reesskennedy.com/compression-enhancer/

It's PHP so super easy to run and then runs some shell commands to get the original creation and add it back after compression. I use it every day!

Could be translated to Python or anything. Perhaps some of your do something similar already and I know this is a request to add this directly into PNGQuant but just sharing a solution!!!!
