### ISSUE TITLE
While installing pngquant getting error

### ISSUE THREAD

**Issue by ravitejamsr** [kornelski/pngquant#361]
Hi

After running cargo build --release command getting error as 
**failed to get `imagequant-sys` as a dependency of package `pngquant v2.12.6**

**Comment by kornelski** [comment]
Can you post full error? There should be explanation why it failed.

**Comment by ravitejamsr** [comment]
@kornelski I fallowed the steps based on [this](https://pngquant.org/install.html) and created the file pngquant.exe file in target/release folder but when i run pngquant -V its showing as '**pngquant' is not recognized as an internal or external command** How i can check its installed or not ?

**Comment by kornelski** [comment]
Great!
