### ISSUE TITLE
Configure: Do Not Override Default Deployment Target

### ISSUE THREAD

**Issue by bdkjones** [kornelski/pngquant#366]
The configure script, on lines 351-354, forces `-mmacosx-version-min=10.7` 

This should not be done if the `$MACOSX_DEPLOYMENT_TARGET` environment variable is set. If it is, THAT value should always take precedence, because it's highly likely that the dependent libraries (libpng, libz, etc.) were built with the deployment target specified globally. The Configure script currently gets into a situation where the dependent libraries might have a deployment target that is higher than the `10.7` value PNGQuant is forcing.

**Comment by bdkjones** [comment]
Apple's docs suggest that the ENV value should override `-mmacosx-version-min`, but after building I'm getting warnings that libpng and libz were built for newer versions than 10.7.

**Comment by kornelski** [comment]
Ok, I've made it unset if `MACOSX_DEPLOYMENT_TARGET` is set. I've also bumped minimum sdk to 10.9.

**Comment by bdkjones** [comment]
Thanks!

-Bryan
