### ISSUE TITLE
Cannot open xxx.png for reading，but the file has created...

### ISSUE THREAD

**Issue by df257** [kornelski/pngquant#369]
![image](https://user-images.githubusercontent.com/7835444/102615946-b775e980-4171-11eb-99cf-65cbcb4dfa44.png)
![image](https://user-images.githubusercontent.com/7835444/102616021-d5dbe500-4171-11eb-8484-1dadcb0ae326.png)

**Comment by zvezdochiot** [comment]
@df257 say:
>`pngquant -- test.png --ext new.png`

```sh
pngquant --ext new.png -- test.png
```
See:
```sh
pngquant --help
```

**Comment by kornelski** [comment]
`--` means *everything* after that is a file name. So `-- --ext` reads a file called "--ext".
