### ISSUE TITLE
Which is the latest stable version?

### ISSUE THREAD

**Issue by szhorvat** [kornelski/pngquant#377]
The latest tag on GitHub is 2.14.1, however, the latest release indicated on https://pngquant.org/ is 2.13.1. Which one is recommended for production use?

**Comment by kornelski** [comment]
2.14.1 is the latest, and you can use it.

I forgot to update the website, because 2.14 was mainly about [the Rust interface](https://lib.rs/crates/imagequant), and it doesn't affect the `pngquant` executable.

**Comment by szhorvat** [comment]
Thanks for the information! It would be great if you could make a source release (similar to the existing ones for other versions). It makes it easier to include the tool in package managers like MacPorts which don't use `git` directly.
