### ISSUE TITLE
Tests cannot be built from the source archive

### ISSUE THREAD

**Issue by szhorvat** [kornelski/pngquant#378]
The tests cannot be built from the source archive at https://pngquant.org/releases.html

The following steps work from the cloned git repo (tag 2.14.1) but not from the source archive:

```
./configure
make
make test
```

The error for `make test` is 

```
make: *** No rule to make target `test/test.o', needed by `test/test'.  Stop.
```

**Comment by kornelski** [comment]
I'll add them in a next release
