### ISSUE TITLE
Cannot Open file for reading in Ubuntu 21.04 (64 Bit)

### ISSUE THREAD

**Issue by firaki12345-cmd** [kornelski/pngquant#388]
**Specs** : **Ubuntu 21.04 (64 Bit)**

So it works good on normal file names like 23.png, ok.png etc..

What could be the Problem ? My file name 

**10-Croc Panel Chunky Hiker Boots.png**

**102-Don't Bother Lace Up Booties - Nude.png**

They are Shoe names BTW ;)

**Comment by kornelski** [comment]
Spaces are used to separate arguments and multiple file names. File names that contain spaces must be quoted.

**Comment by firaki12345-cmd** [comment]
> Spaces are used to separate arguments and multiple file names. File names that contain spaces must be quoted.

thank you so much :)
