### ISSUE TITLE
no matching package named `imagequant-sys` found

### ISSUE THREAD

**Issue by Des-Nerger** [kornelski/pngquant#393]
I've done:
```bash
$ git clone --recursive https://github.com/kornelski/pngquant.git
$ cd pngquant
$ git checkout tags/2.17.0
$ cargo build --release
```
and got:
```
    Updating crates.io index
error: no matching package named `imagequant-sys` found
location searched: /media/c/Documnts/src/pngquant/lib
required by package `pngquant v2.17.0 (/media/c/Documnts/src/pngquant)`
```
What's wrong here? My rustc version is 1.55.0 (in case it matters), which conforms to the requirements in the pngquant v2.17.0's INSTALL instructions.

**Comment by Des-Nerger** [comment]
Oh, I got it; my bad. I should have also done `(cd lib && git checkout tags/2.17.0)` before building. The issue is resolved.

**Comment by kornelski** [comment]
yeah, after checkout `git submodule init` is needed too. Submodules are terrible ;(

**Comment by lazka** [comment]
It looks like imagequant-sys isn't used anymore (??), so maybe the submodule and the imagequant-sys references could be removed.
