### ISSUE TITLE
pngquant doesn't work inside Windows Docker containers

### ISSUE THREAD

**Issue by Antonytm** [kornelski/pngquant#394]
I have an ASP.NET MVC website, which is hosted in a Docker container based on [Windows Server Core image](https://hub.docker.com/_/microsoft-windows-servercore), 1809-amd64 tag.

I want to run `pngquant` inside this container in order to optimize `png` images.

I got an exception:
```
"C:\tools\pngquant.exe --force --output "C:\Windows\TEMP\tmp3D51.png" -- "C:\Windows\TEMP\tmp3D50.png" exited with unexpected exit code -1073741515.
```

I try to troubleshoot the issue. 
1. I connect to Docker container using shell
2. I try to run `pngquant.exe` using shell (at least to see help)

**Expected result:**
I should see help information (example from the website hosted locally, not in the container)
![image](https://user-images.githubusercontent.com/647813/152673595-3613b2fd-a644-45c3-bd71-9061e4a285e4.png)

**Actual result:**
The command exits silently.
![image](https://user-images.githubusercontent.com/647813/152673531-3819a5c8-fca5-4b19-b17e-8da33396286e.png)

**Comment by Antonytm** [comment]
Are there any dependencies that are probably missed in the container?

**Comment by jibsen** [comment]
Looking at pngquant.exe for 2.17, it looks like you might need a Microsoft Visual C++ Redistributable to run it.

I don't know if the container has such, but a quick google gave [this page](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170).

The screenshot you have shows pngquant 2.12, so I don't know if you might need a different version for that.

**Comment by Antonytm** [comment]
@jibsen Thank you!

The image that I used doesn't have *Microsoft Visual C++ Redistributable*.

I have added these lines to my `dockerbuild` file:
```
RUN Powershell Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
RUN choco install vcredist-all -y
```
(it install this *choco* package: https://community.chocolatey.org/packages/vcredist-all)
and it started to work!

Do you know what exact version of *Microsoft Visual C++ Runtime* is required? recommended? enough to have?
(to avoid installation of all version to my image)

**Comment by jibsen** [comment]
Glad to hear that worked!

Try this one: https://community.chocolatey.org/packages/vcredist140

**Comment by Antonytm** [comment]
Yes, it also works.

**Comment by Antonytm** [comment]
I think the issue could be closed, but better to document it.
