### ISSUE TITLE
Input and output parameters

### ISSUE THREAD

**Issue by acteds** [kornelski/pngquant#395]
Batch (.bat)

**Use parameters:**

> pngquant.exe --force --speed 1 **- >**"%%~a-out.png" **<**"%%~a"

When used in batches, sometimes:
1.  The output file size is 0
2.  The output file is not a valid image and cannot be opened
3.  The image content of the output file is partially lost and can be opened

**Use parameters:**

> pngquant.exe --force --speed 1 **--output** "%%~a-out.png" "%%~a"

No above problems, what is the reason?

**Comment by kornelski** [comment]
When you use `>`, pngquant isn't creating the file, your shell (cmd.exe) is. It's outside of my control.

**Comment by acteds** [comment]
> When you use `>`, pngquant isn't creating the file, your shell (cmd.exe) is. It's outside of my control.

I see.
