### ISSUE TITLE
Windows Build - Executing from current directory should include exclusion for pngquant.exe 

### ISSUE THREAD

**Issue by LtFarns** [kornelski/pngquant#400]
I was able to successfully install and execute the latest build  2.17.0 on my windows machine. 

The pngquant.exe --ext .png --force 256 * worked as intended on my current directory.
However, error: cannot decode image pngquant.exe occured at the end instead of expected success message. 
Thankfully this was the last file processed by the app. 

Regards

**Comment by kornelski** [comment]
I'm not planning to do this. `*` means all files, and there's infinite number of wrong files it can select. Use `*.png` or something more specific like `assets/*.png`.
