### ISSUE TITLE
Using more than 4 bits per channel with posterization

### ISSUE THREAD

**Issue by rmn20** [kornelski/pngquant#401]
Not sure why it is limited to 4 bits. Maybe limit could be changed? RGB555 and 565 are also very common.

**Comment by kornelski** [comment]
The value is number of bits to remove, not bits to keep. RGB555 removes 3 bits, not 4.

**Comment by rmn20** [comment]
Maybe this could be specified in option description? What about RGB565?

**Comment by kornelski** [comment]
Only one value for all channels is supported. For 565 use posterization=2.
