### ISSUE TITLE
Is it possible to keep fully transparent (0 alpha) areas of image fully transparent?

### ISSUE THREAD

**Issue by Alexander--** [kornelski/pngquant#402]
I have been fiddling with pngquant (version 3.1.0 from Arch Linux repositories) and noticed, that it sometimes makes fully transparent colors not-so-transparent when told to dramatically reduce number of colors:

````
pngquant 2 ./ic_unholy_orig.png
````

Original image: ![ic_unholy_orig](https://user-images.githubusercontent.com/1107390/223656968-23281732-dbe1-4747-b246-a10bb8b9439f.png)
After quantization: ![ic_unholy_orig-fs8](https://user-images.githubusercontent.com/1107390/223656997-598905bb-e970-4180-9eb4-09f8482c6e9a.png)

The new image looks fine at the first glance, but it's second color (the one that fills most of image) actually has alpha value of 1 instead of initial value of 0. This is rather annoying, because the code that checks alpha == 0 for transparent pixels is no longer working as intended.

Can this be fixed?

**Comment by kornelski** [comment]
Yeah, I think it'd make sense to special-case alpha==0.

**Comment by kornelski** [comment]
This has been fixed in 7b3819e
