### ISSUE TITLE
not create .exe after build

### ISSUE THREAD

**Issue by qiudaoermu** [kornelski/pngquant#407]
git clone -b msvc --recursive https://github.com/kornelski/pngquant.git
cd pngquant
cargo build --release

warning: msvc-dist/ directory not present. MSVC builds may fail
what's the matter?

**Comment by kornelski** [comment]
You can ignore the warning. It's outdated and I'll remove it. 

The operation succeeded and has created target/release/pngquant.exe

**Comment by qiudaoermu** [comment]
i use mac, 😁,shou i use windows to compile?

**Comment by kornelski** [comment]
In that case it has successfully built a mac executable in `target/release/pnguant`. 

Windows is not required.
