### ISSUE TITLE
missing malloc fail check in read_chunk_callback

### ISSUE THREAD

**Issue by void0red** [kornelski/pngquant#408]
we perform a test on pngquant and find two bugs in read_chunk_callback.

https://github.com/kornelski/pngquant/blob/4a48cfc6e531cd5c07fef8398495c345f09c13ba/rwpng.c#L147
https://github.com/kornelski/pngquant/blob/4a48cfc6e531cd5c07fef8398495c345f09c13ba/rwpng.c#L151

it may cause NPD later since malloc fails when oom.

**Comment by kornelski** [comment]
Thanks!
