### ISSUE TITLE
Homebrew Version

### ISSUE THREAD

**Issue by nwhite89** [kornelski/pngquant#412]
Currently homebrew https://formulae.brew.sh/formula/pngquant is still only supporting v2.18 as the version for PNGQuant it would be good to get this updated to the new v3 if possible.

Thanks in advance

**Comment by samford** [comment]
I [updated the `pngquant` formula](https://github.com/Homebrew/homebrew-core/pull/156647) to use the latest crate version (3.0.2) and it will track crate releases going forward (as suggested on the [first-party releases page](https://pngquant.org/releases.html)), so this can be closed.

**Comment by kornelski** [comment]
Thank you
