### ISSUE TITLE
Images hold often less colors than requested

### ISSUE THREAD

**Issue by frkay** [kornelski/pngquant#90]
On various samples even when I ask for 256 colors in the resulting image I get less (down to 248 for some).
Files produced by pngquant apparently have 256 palette entries, but once optimized with pngrewrite, pngout or zopflipng the color count goes often down to 255 or 254 sometimes even less.
Here are some PNG-32 that trigger the problem (see next comment for steps to reproduce it).

![sample_66](https://cloud.githubusercontent.com/assets/2280807/2869514/fa88317a-d273-11e3-8371-48c11d194a81.png)
![sample_56](https://cloud.githubusercontent.com/assets/2280807/2869516/fa95ea22-d273-11e3-89a0-05d1a3b4fccb.png)
![sample_49](https://cloud.githubusercontent.com/assets/2280807/2869520/fa9afd6e-d273-11e3-9193-237a8beb417e.png)
![sample_24](https://cloud.githubusercontent.com/assets/2280807/2869522/faa841e0-d273-11e3-981b-bec8c28eb79d.png)
![sample_13](https://cloud.githubusercontent.com/assets/2280807/2869528/faba8d8c-d273-11e3-8904-f790cb5fc4c3.png)
![sample_10](https://cloud.githubusercontent.com/assets/2280807/2869529/fabbe240-d273-11e3-94a5-333baf24b586.png)

**Comment by petrdiblik** [comment]
+1
I have been monitoring this bug for a long time, with many images.
Could that be fixed please?

**Comment by dsvensson** [comment]
Noticed this as well. My use case is an image that's black and transparent and is converted to a 1 bit palette, the 3D engine that it's used in expects 256 bit palette so it breaks.

**Comment by kornelski** [comment]
I do not expect this to be an issue in v4.0.0. Please file a new bug with example images if you still find problems.
